### PR TITLE
Support of binary messages (#52)

### LINKED ISSUE #52: How should I handle binary messages ?
I need to handle binary messages.

It appears that the data coding of DeliverSM PDU is not exposed, and in `codingMap` (`codings.go:209)`, data coding 0x02 and 0x04 are not supported (datacoding codes for 8-bit binary).
It's the same problem for SubmitSM.

Have you ever met this issue ?
Do you intend to support binary messages in the future ?
I can make a pull request if you wish, any suggestions of implementation are welcome ;).

### PR DESCRIPTION
**Pull request by goten4**
Here is another proposal to fix #52 including @bachhh suggestions

Cancel and replace #53

### CODE REVIEW

**Comment by bachhh** [comment]
lgtm @goten4  thanks for the PR.

I still feel like we need to address the underlying false assumption: that a ShortMessage need to contains human-readable string. While the reality is some system might choose to put small binary data in a ShortMessage.

**Review by bachhh — APPROVED** [review]

**Comment by goten4** [comment]
> lgtm @goten4 thanks for the PR.
> 
> I still feel like we need to address the underlying false assumption: that a ShortMessage need to contains human-readable string. While the reality is some system might choose to put small binary data in a ShortMessage.

Totally agree

**Review by linxGnu — APPROVED** [review]
LGTM

**Comment by linxGnu** [comment]
@goten4 great job :+1:

**Comment by arshabbir** [comment]
I am trying to set the data coding scheme to 0xf6(246) to test SAT push messaging in a production environment. I couldn't find a way to provision the DCS explicitly for this.  Could anyone please help here.. Thank you very much.

**Comment by linxGnu** [comment]
@arshabbir could you please create an issue for your request instead of leaving your comment here :) Thank you very much for using gosmpp.

**Pull request merged**
