### PR TITLE
NO-ISSUE Enhance CI

### PR DESCRIPTION
**Pull request by septs**

### CODE REVIEW

**Comment by septs** [comment]
image

from https://github.com/linxGnu/gosmpp/actions/runs/263702893

image

from https://github.com/linxGnu/gosmpp/actions/runs/263875962

reduce time, ≈ 40s run duration

**Comment by septs** [comment]
@linhduonggnu

**Comment by linxGnu** [comment]
Lgtm. Thank you very much. Its great!

**Comment by linxGnu** [comment]
@bachhh please take a look and merge this pr

**Comment by bachhh** [comment]
LGTM, I think we should migrate to go.15 soon.

**Pull request merged**
