### PR TITLE
fix fail test in pdu/SubmitMulti_test.go

### LINKED ISSUE #92: TestSubmitMulti fails due to a type in hexValue
A character was deleted by mistake for expected value in TestSubmitMulti, so the test fails with message `encoding/hex: odd length hex string`

### PR DESCRIPTION
**Pull request by goten4**
Fixes #92

I also added `smsc` in `.gitignore` to prevents add the binary in commits

### CODE REVIEW

**Review by linxGnu — APPROVED** [review]
LGTM. Thank you

**Comment by laduchesneau** [comment]
I see the error I made. When I modified EsmClass from 77 (0x4d) to 13 (0xd) i forgot to add the  **0** (x**0**d)

Sorry about that.

**Comment by linxGnu** [comment]
@laduchesneau no worry, could you please make a fix

**Comment by laduchesneau** [comment]
fix already applied by this merge from @goten4

**Comment by linxGnu** [comment]
I see. Thank you for the info. I misunderstand your sentence

**Pull request merged**
