### PR TITLE
new OnAllPDU seeting that lets users choose to handle all PDUs from SMSC

### PR DESCRIPTION
**Pull request by laduchesneau**
As propose in #96  and in  #107 

What:
This feature allows the ESME to control PDU response by using a new setting that will handle all PDU. This proposed feature does not interfere with current user behaviour. 

Why:
Some ESME need to validate incoming PDUs, like DeliverSm and DataSM, before returning a response.

How:
- new `OnAllPDU` setting that lets users choose how to handle PDUs from SMSC
- If the user sets new setting, it will overide `OnPDU`
- Respond function added to Receivable and Transceivable, to allow Respond/Submit for the response

Warning:
This setting, if set, overrides `OnPDU` and bypass all auto response feature, Enquirelink and Unbind request must be handled by user.

Added a new example called `transcceiver_with_manual_response` to see how it can be used, moved old example in `transceiver_with_auto_response` .

### CODE REVIEW

**Comment by laduchesneau** [comment]
I never like adding `func (t *receivable) Respond(p pdu.PDU) error` to both receivable and transceivable. What if OnAllPDU had a return argument ?
```
OnAllPDU func(pdu pdu.PDU) pdu.PDU
```
And receivable just check if the return pdu wasnt nil.
```
if t.settings.OnAllPDU != nil {
    r := t.settings.OnAllPDU(p)
    if r != nil {
        t.settings.response(r)
    }
    return
}
```

**Review by linxGnu — APPROVED** [review]
It's awesome. LGTM.

**Comment by linxGnu** [comment]
@laduchesneau 
Yes, I like the second approach too:

```go
if t.settings.OnAllPDU != nil {
    r := t.settings.OnAllPDU(p)
    if r != nil {
        t.settings.response(r)
    }
    return
}
```

**Comment by laduchesneau** [comment]
Return value added to `OnAllPDU`, I like this a lot more, code is simpler.

Removed a lot of change from initial commit in PR. When/if it gets merge, recommend squashing all commits.

**Review by linxGnu — APPROVED** [review]

**Comment by linxGnu** [comment]
LGTM. Could you please have a look too @goten4

**Pull request merged**
